### PR TITLE
Fix file paths for Windows platform

### PR DESCRIPTION
**Pull request by utak3r**
With some configurations of params it wasn't working on Windows platform. With this simple fix it's working without issues.

### CODE REVIEW

**Comment by LanceGao97** [comment]
Hi  utak3r, 
Thanks very much for leading the way and mention this fix,  i will try this script later at night.

**Comment by LanceGao97** [comment]
> With some configurations of params it wasn't working on Windows platform. With this simple fix it's working without issues.


sorry,   tested it,  but it's still not working,

**Comment by vladmandic** [comment]
This fix doesn't do anything, os.path.join already handles OS specific separators. If there is an issue with paths, it's somewhere else.
Sorry for not paying attention earlier, just been busy. Will take a look.

**Comment by utak3r** [comment]
That's not true. It has issues with forming the %d string for images serie without it. And it fixes it for me.

**Comment by vladmandic** [comment]
python says they are the same:
```log
python
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
>>> import ntpath
>>> import os
>>> print(os.sep, ntpath.sep, os.sep == ntpath.sep)
\ \ True
```
not to mention that `ntpath` is not even standard python library and would need to be added to requirements.

**Comment by utak3r** [comment]
I'm only saying, that by debugging, I saw errors in a string, when trying to build a whole string, mainly around '%07d' part - and with this fix I got rid of it. Maybe it's only for my config, I don't know. You should know docs are only docs ;)

**Comment by InResponse** [comment]
The issue isn't the file names. Certain prompts (e.g., those with newlines) end up setting `params['description']` to an unsafe string, because `params['prompt']` is set to an unsafe string right beforehand. Here:

```
params['seed'] = v['all_seeds'][index]
params['prompt'] = v['all_prompts'][index]
params['short_name'] = str(params['seed']) + '-' + safestring(params['prompt'])[:name_length]
params['outfile'] = os.path.join(params['outpath'], params['short_name'] + suffix)
params['sequence'] = f'{iter:02d}{batch:02d}{(skip_steps + 1):03d}'
params['description'] = '{prompt} | negative {negative} | seed {seed} | sampler {sampler} | cfgscale {cfgscale} | steps {steps} | last {laststep} | model {model} | embedding {embedding} | faces {faces} | timestamp {timestamp} | interpolation {interpolation}'.format(**params)
current_step = 0 # reset back to zero
```

`v['all_prompts'][index]` isn't safe. It needs to be. As in:

```
params['prompt'] = safestring(v['all_prompts'][index])
```

There. Fixed. No need for importing ntpath or the rest of this pull request. Just don't try to use an unsafe string in a command. It's bad juju.

**Pull request closed without merging**
